read modelName from config file
brian-intel/model_server pull request #3
Opened 2023-05-04 02:04 UTC by vli11

2023-05-05 21:34 UTC, marcpfuller approved these changes

2023-05-05 22:09 UTC, brian-intel approved these changes

2023-05-08 15:41 UTC, jim-wang-intel requested changes

2023-05-08 15:41 UTC, jim-wang-yutsung commented on src/go/go-binding/utilities/util.go
> +}
would suggest parsing config.json use json unmarshal instead of this ad-hoc approach

2023-05-09 18:31 UTC, jim-wang-intel commented on src/go/go-binding/utilities/util.go
> +func GetModelNameFromConfig(configfilepath string) ([]string, error) {
```suggestion
func GetModelNameListFromConfig(configfilepath string) ([]string, error) {
```

2023-05-09 18:31 UTC, jim-wang-intel commented on src/go/go-binding/capi.go
> +	modelNameList, err := utilities.GetModelNameFromConfig(modelConfigPath)
```suggestion
	modelNameList, err := utilities.GetModelNameListFromConfig(modelConfigPath)
```

2023-05-09 18:39 UTC, jim-wang-intel approved these changes
LGTM

2023-05-09 18:41 UTC, merged